### ISSUE TITLE
Not displayed in Store

### ISSUE THREAD

**Issue by Unrud** [flathub/com.openwall.John#1]
The app is missing: https://flathub.org/apps/details/com.openwall.John
I think this is caused by one or multiple of the following issues:

  * The icon name should be ``com.openwall.John``:
https://github.com/flathub/com.openwall.John/blob/69c7754b5f4a418592291283ee09daf04b00cffc/com.openwall.John.desktop#L10
  * The icon should be installed to ``/app/share/icons/hicolor/256x256/apps/com.openwall.John.png``:
https://github.com/flathub/com.openwall.John/blob/69c7754b5f4a418592291283ee09daf04b00cffc/com.openwall.John.json#L87
  * (Icons with a resolution of 64x64 and 128x128 should be provided.)

**Comment by bilelmoussaoui** [comment]
The app is missing because Flathub doesn't support CLI apps on the frontend yet.

**Comment by claudioandre-br** [comment]
Thanks for the information provided.
