### ISSUE TITLE
Error: No command specified  See ‘flatpak --help’

### ISSUE THREAD

**Issue by sleepy124** [flathub/com.openwall.John#9]
so when i insatalled it with flathub then ran the command to run it nothing happens. then i click on it in my chrome os tab and it brings me to linux terminal loads then says

Error: No command specified

See ‘flatpak --help’

and i dont understand what to do now?

**Comment by claudioandre-br** [comment]
Let me understand your problem: did you open a CLI linux terminal (command line interface), tried all these commands and none gave you an output?

```sh
flatpak run com.openwall.John 
flatpak run com.openwall.John -list=build-info
flatpak run com.openwall.John --help
```

One possible explanation I know of (user reported at some point in the past) is that your CPU is too old (AVX is not supported). BTW: do you know something about your CPU?
****

Well, the previous version of the flatpak package will work fine on an old CPU (one that only supports SSE2).

Probably the command below allows you to run `john` even on an old CPU [1].
```sh
 flatpak --user make-current com.openwall.John 1.9.0J1
``` 

[1] I'm not very good at flatpak internals, but the command should force/try to use the previous package version.
****

BTW:
- I know nothing about Chrome OS, I must focus on the CLI.
- on a regular Linux, this is agood source of info: `cat /proc/cpuinfo | grep flags | grep avx`

**Comment by sleepy124** [comment]
hello.. yes i tred all 3 of the first command and they dont give any output. when i tried  flatpak --user make-current com.openwall.John 1.9.0J1" it says "[ ](error: com.openwall.John/*unspecified*/1.9.0J1 not installed)" debain 11 is what i have.

**Comment by sleepy124** [comment]
processor       : 3
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 32
model name      : AMD 3015Ce with Radeon Graphics
stepping        : 1
microcode       : 0x1000065
cpu MHz         : 1197.749
cache size      : 512 KB
physical id     : 3
siblings        : 1
core id         : 0
cpu cores       : 1

**Comment by claudioandre-br** [comment]
It is a weak CPU, but it should work. 

Well, I don't know what could cause this, please try to debug using flatpak tools and report back. E.g.:

```sh
flatpak run --command=sh --devel com.openwall.John

# you are now inside flatpak runtime/sandbox
ls -lah /app
ls -lah /app/bin
/app/bin/john          # run john
/app/bin/john/john-avx      # run john
``` 

Get some ideas at https://docs.flatpak.org/en/latest/debugging.html. You'll probably get an error message sooner or later, which will be a hint as to what's wrong.

The flatpak itself works and was tested. So, it is related to you environment or so. Please, try to narrow it.

**Comment by claudioandre-br** [comment]
>  "error: runtime/org.freedesktop.Sdk/x86_64/23.08 not installed

You need to install the Sdk.

```
 sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo # flatpak repository
 sudo flatpak install -y flathub org.freedesktop.Sdk//23.08 # Probably. This is a regular Linux session.
```

**Comment by sleepy124** [comment]
everytime i do a command it says "Illegal instruction (core dumped)"

**Comment by claudioandre-br** [comment]
> everytime i do a command it says "Illegal instruction (core dumped)"

Which one? 

Anyway, have you tried the `/app/bin/john/john-avx` (inside the sandbox)?

**Comment by sleepy124** [comment]
when i type any "john/zip2john" anything related to john the stripper.

**Comment by sleepy124** [comment]
[📦 com.openwall.John ~]$ /app/bin/john/john-avx
sh: /app/bin/john/john-avx: Not a directory
[📦 com.openwall.John ~]$

**Comment by claudioandre-br** [comment]
Ok, my fault. It is:

`/app/bin/john-avx`

**Comment by sleepy124** [comment]
📦 com.openwall.John ~]$ /app/bin/john-avx
Created directory: /home/sighan364/.john
John the Ripper 1.9.0-jumbo-1+bleeding-39db7dd63e 2023-09-20 17:02:33 -0300 [linux-gnu 64-bit x86_64 AVX AC]
Copyright (c) 1996-2023 by Solar Designer and others
Homepage: https://www.openwall.com/john/

Usage: john-avx [OPTIONS] [PASSWORD-FILES]

Use --help to list all available options.
[📦 com.openwall.John ~]$ john
Illegal instruction (core dumped)
[📦 com.openwall.John ~]$

**Comment by sleepy124** [comment]
like see? when i use john or any command related it says illegal instruction-

**Comment by sleepy124** [comment]
sighan364@penguin:~$ $ flatpak run --command=john-avx-omp com.openwall.John <options>
-bash: syntax error near unexpected token `newline'
sighan364@penguin:~$

**Comment by claudioandre-br** [comment]
> sighan364@penguin:~$ $ flatpak run --command=john-avx-omp com.openwall.John -bash: syntax error near unexpected token `newline' sighan364@penguin:~$

The `$` is not part of the command (just remove it before running the command).

**Comment by claudioandre-br** [comment]
I'm able to reproduce the failure now. 

I'll open an issue to document it.

**Comment by sleepy124** [comment]
i know that $ is not apart it comes when i type command im in ChromeOS linuxc terminal

**Comment by sleepy124** [comment]
sighan364@penguin:~$ flatpak run --command=john-avx2-omp com.openwall.John # if you have AVX2
John the Ripper 1.9.0-jumbo-1+bleeding-39db7dd63e 2023-09-20 17:02:33 -0300 OMP [linux-gnu 64-bit x86_64 AVX2 AC]
Copyright (c) 1996-2023 by Solar Designer and others
Homepage: https://www.openwall.com/john/

Usage: john-avx2-omp [OPTIONS] [PASSWORD-FILES]

Use --help to list all available options.
sighan364@penguin:~$ john

**Comment by sleepy124** [comment]
https://imgur.com/a/5WHqW67 here is a screen shot of what it says. it kicks me out o f the john thing ?

**Comment by sleepy124** [comment]
i uninstalled John and installed again and it says this

 "sighan364@penguin:~$ flatpak install flathub com.openwall.John
Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 2

com.openwall.John permissions:
    file access [1]

    [1] home


        ID                      Branch      Op      Remote       Download
 1. [✓] com.openwall.John       stable      i       flathub      74.8 MB / 72.3 MB

Warning: Not exporting file com.openwall.John.appdata.xml of unsupported type.
Installation complete.
sighan364@penguin:~$ "


why does it give a WARNING ?

**Comment by sleepy124** [comment]
well i entered john the ripper with the command 

flatpak run --command=sh --devel com.openwall.John

# you are now inside flatpak runtime/sandbox
ls -lah /app
ls -lah /app/bin
/app/bin/john          # run john
/app/bin/john-avx      # run john


but the only command i can runt is john-avx and john-avx2 and all those with avx. everything elese says  Illegal instruction (core dumped)
